# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            PTDN
tagline:          'Plain-Text Defined Networking'
description:      'Redes definidas por texto e explicadas de um modo simples para você.'
url:              https://ptdn.github.io/
baseurl:          /

author:
  name:           'Fernando Gomes'
  url:            https://twitter.com/mdo

gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb

paginate:         5

paginate_path: "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
